apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-dashboard-app
  labels:
    app: ops-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ops-dashboard
  template:
    metadata:
      labels:
        app: ops-dashboard
    spec:
      containers:
        - name: ops-dashboard-container
          image: srikant25/ops-dashboard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
