apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-dashboard-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ops-dashboard-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "events", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-dashboard-role-binding
subjects:
- kind: ServiceAccount
  name: ops-dashboard-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ops-dashboard-role
  apiGroup: rbac.authorization.k8s.io
