apiVersion: v1
kind: Service
metadata:
  name: ops-dashboard-service
spec:
  type: NodePort
  selector:
    app: ops-dashboard
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
